Agentforce Hackathon Source Code/force-app/main/default/objects/Test_Drive__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Test Drive</relationshipLabel>
    <relationshipName>Test_Drive</relationshipName>
    <type>Lookup</type>
</CustomField>

Agentforce Hackathon Source Code/force-app/main/default/objects/Test_Drive__c/fields/Dealership__c.field-meta.xml
<CustomField>
    <fullName>Dealership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The dealership where the test drive will take place</description>
    <label>Dealership</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Test Drives</relationshipLabel>
    <relationshipName>TestDrives</relationshipName>
    <type>Lookup</type>
</CustomField>

Agentforce Hackathon Source Code/force-app/main/default/objects/Test_Drive__c/fields/PreferredTimeSlot__c.field-meta.xml
<CustomField>
    <fullName>PreferredTimeSlot__c</fullName>
    <label>Preferred Time Slot</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>09:00 AM - 10:00 AM</fullName>
            </value>
            <value>
                <fullName>10:00 AM - 11:00 AM</fullName>
                <default>true</default>
                <label>10:00 AM - 11:00 AM</label>
            </value>
            <value>
                <fullName>11:00 AM - 12:00 PM</fullName>
            </value>
            <value>
                <fullName>12:00 PM - 01:00 PM</fullName>
            </value>
            <value>
                <fullName>01:00 PM - 02:00 PM</fullName>
            </value>
            <value>
                <fullName>02:00 PM - 03:00 PM</fullName>
            </value>
            <value>
                <fullName>03:00 PM - 04:00 PM</fullName>
            </value>
            <value>
                <fullName>04:00 PM - 05:00 PM</fullName>
            </value>
            <value>
                <fullName>05:00 PM - 06:00 PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Agentforce Hackathon Source Code/force-app/main/default/classes/TestDriveController.cls
public with sharing class TestDriveController {
    
    @AuraEnabled
    public static String createTestDrive(String dealerId, String assetId, String slotTime, String slotDate) {
        Test_Drive__c record = new Test_Drive__c(
            Dealership__c = dealerId,
            Asset__c = assetId,
            PreferredTimeSlot__c = slotTime,
            Preferred_Date__c = Date.valueOf(slotDate)
        );
        
        insert record;
        return (String)record.Id;
    }
}